# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginMaitre
                                 A QGIS plugin
 Gestion des distributions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-25
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os.path

from qgis.PyQt.QtCore import QSize
from qgis.PyQt.QtWidgets import QInputDialog, QLabel,QAction,QListWidgetItem,QMenu,QListWidget
from qgis.utils import plugins

from .maj import *
from .dlg_install_plugins import *


class PluginMaitre:
    def __init__(self, iface):


        # log(f"Initialisation de : {TITRE}",reset=True)

        self.path_xml = None
        self.toolbar = None
        # dico de toutes les toolbars pour gérer la suppression
        self.toolbars = {}

        self.dlg = None
        self.dlgaddonglet = None
        self.iface = iface
        # self.timer = None

        # self.maj = MajPlugins(self.iface)
        self.installer = InstallerDialog(self)
        self.maj = MajPlugins(self.iface, self.installer)

        # Declare instance attributes
        # self.actions = []

        # MENU
        self.menu = QMenu(self.iface.mainWindow())
        self.menu.setObjectName("IGN")
        self.menu.setTitle("IGN")
        self.menu_requete = None
        self.menu_config = None

        # list contenant les plugins IGN contenu dans le repertoire des plugins
        self.plugin_ign = []
        # liste des onglets
        self.list_onglet = []

        # list contenant les plugins cochés
        self.listplugin_coche = []

        self._plugins_installes = self.getlistplugin_ign()
        self.path_xml = Path(os.path.dirname(__file__), DOSSIER_ONGLET, "tabwidget.xml")
        if not os.path.exists(self.path_xml):
            self.initXML()

        self.add_plugin_in_toolbars()
        self.init_menuIGN()

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = True

    # creation du menu IGN
    def init_menuIGN(self):
        self.supr_plugin_to_menu()

        current_directory = os.path.dirname(__file__)
        # Remonter d'un niveau
        parent_directory = os.path.abspath(Path(current_directory, os.pardir))

        # ************************************************************************
        # Installation des plugins IGN
        icon_path = Path(os.path.dirname(__file__)) / "icons" / "install_plugins.png"
        action = QAction(QIcon(str(icon_path)), "Installation des plugins IGN", self.iface.mainWindow())
        action.triggered.connect(self.on_show_dial_install_plugins_ign)
        self.menu.addAction(action)

        # ************************************************************************
        # Configuration
        icon_path = Path(os.path.dirname(__file__)) / "icons" / "icon.png"
        action = QAction(QIcon(str(icon_path)),"Configuration",self.iface.mainWindow())
        action.triggered.connect(self.run)
        self.menu.addAction(action)

        # ************************************************************************
        # menu "Requêtes"
        # self.menu_requete = QMenu("Requêtes", self.iface.mainWindow())
        # self.menu.addMenu(self.menu_requete)
        # requete = QAction("Lancer une requêtes", self.iface.mainWindow())
        # requete.triggered.connect(self.on_requete)
        # self.menu_requete.addAction(requete)
        # # # action dans le sous-menu
        # # requete_unique = QAction("Lancer une requête unique", self.iface.mainWindow())
        # # requete_unique.triggered.connect(self.on_requete_unique)
        # # requete_enchaine = QAction("Lancer une requête enchainée", self.iface.mainWindow())
        # # requete_enchaine.triggered.connect(self.on_requete_enchaine)
        # # self.menu_requete.addAction(requete_unique)
        # # self.menu_requete.addAction(requete_enchaine)
        self.menu.addSeparator()

        # ************************************************************************

        # ************************************************************************
        # documentation bduni
        icon_path = Path(os.path.dirname(__file__), "icons", "spec.png")
        action = QAction(QIcon(str(icon_path)) ,"Documentation BDTopo",self.iface.mainWindow())
        action.triggered.connect(affiches_spec_bdtopo)
        self.menu.addAction(action)
        self.menu.addSeparator()
        # ************************************************************************

        # ************************************************************************
        # menu "Documentation plugins"
        self.menu_doc_plugins = QMenu("Documentations des plugins ...", self.iface.mainWindow())
        self.menu.addMenu(self.menu_doc_plugins)
        for plugin in self._plugins_installes:

            icon = Path(parent_directory, plugin, "icons", "icon_principal.png")
            doc_plugin = QAction(QIcon(str(icon)),f"{plugin}", self.iface.mainWindow())

            doc_plugin.triggered.connect(lambda *_, plugin1=plugin: self.on_affiche_doc_plugin(plugin1))
            self.menu_doc_plugins.addAction(doc_plugin)
        self.menu.addSeparator()

        # ************************************************************************
        # autre plugin
        for plugincoche in self.get_plugin_coche_fromXML(MENU_IGN):
            if plugincoche in self.plugin_ign:
                icon_path = Path(parent_directory,plugincoche,"icons","icon_principal.png")
                action = QAction(QIcon(str(icon_path)),plugincoche,self.iface.mainWindow())
                action.triggered.connect(lambda checked, plugincoche1=plugincoche: self.runplugin(plugincoche1))
                self.menu.addAction(action)
        self.menu.addSeparator()
        # ************************************************************************


        # ************************************************************************
        # Aide
        icon_path = Path(os.path.dirname(__file__)) / "icons" / "aide.png"
        action = QAction(QIcon(str(icon_path)), "Aide", self.iface.mainWindow())
        action.triggered.connect(self.apropos)
        self.menu.addAction(action)

        # *********************************************
        menuBar = self.iface.mainWindow().menuBar()
        menuBar.insertMenu(self.iface.firstRightStandardMenu().menuAction(), self.menu)

    def get_lien_doc_from_metadata(self, plugin):
        plugins_dir = os.path.join(QgsApplication.qgisSettingsDirPath(),"python","plugins")
        fic_metadata = os.path.join(plugins_dir, plugin, "metadata.txt")
        with open(fic_metadata, "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("homepage="):
                    lien = line.strip().split("=")[1]
                    if lien ==  r"http://homepage":
                        afficheerreur("Attention", f"La documentation du plugin {plugin} est absente.")
                        return None
                    return lien
            return None

    def get_icon_from_metadata(self, plugin):
        plugins_dir = Path(QgsApplication.qgisSettingsDirPath(),"python","plugins")
        fic_metadata = Path(plugins_dir, plugin, "metadata.txt")
        with open(fic_metadata, "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("icon="):
                    lien = line.strip().split("=")[1]
                    if lien ==  r"icon":
                        afficheerreur("Attention", f"L'icone du plugin {plugin} est absente.")
                        return None
                    return plugins_dir / plugin / lien
            return None

    def on_affiche_doc_plugin(self,plugin):
        lien_doc = self.get_lien_doc_from_metadata(plugin)
        if lien_doc:
            webbrowser.open(lien_doc)

    def on_requete(self):
        self.runplugin("IGN_requetes")

    # ==================================================
    # suppression de toutes les barres d'outils
    def suppr_all_toolbar(self):
        for toolbar in self.toolbars.values():
            toolbar.setParent(None)
        self.toolbars.clear()
        self.toolbar = None

    # ==================================================
    # mise a jour des toolbars et du menu lors d'ajout de plugins
    def actualiser(self):
        list_plugin_toolbar_coche = []
        # ecrire les plugins cochés dans le xml en fct des onglets des barres d'outils
        for onglet in range(self.dlg.tabWidget.count()):
            list_plugin_toolbar_coche.clear()
            nom_onglet = self.dlg.tabWidget.tabText(onglet)
            widgetlist = self.dlg.tabWidget.widget(onglet)
            for index in range(widgetlist.count()):
                if widgetlist.item(index).checkState() == Qt.CheckState.Checked:
                    list_plugin_toolbar_coche.append(widgetlist.item(index).text())

            # suppression de tous les plugins cochés par barre d'outils du xml
            self.suppr_all_plugincoche_toXML(nom_onglet)
            self.ecrire_plugin_coche_toXML(nom_onglet,list_plugin_toolbar_coche)

        # suppression de tous les plugins cochés du menu IGN
        self.suppr_all_plugincoche_toXML(MENU_IGN)
        liste_plugins_menu_coches = []
        for index in range(self.dlg.listWidget_menu_IGN.count()):
            item = self.dlg.listWidget_menu_IGN.item(index)

            if item.checkState() == Qt.CheckState.Checked:
                liste_plugins_menu_coches.append(item.text())
        self.ecrire_plugin_coche_toXML(MENU_IGN, liste_plugins_menu_coches)

        # ajout, suppression dans la toolbar
        self.add_plugin_in_toolbars()
        self.init_menuIGN()

    # rafraichir les barres d'outils avec liste des plugins installés
    # utils apres installation via un profil
    def refresh_plugins(self):
        self.clean_tabwidget_xml()
        self.add_plugin_in_toolbars()
        self.init_menuIGN()

    def clean_tabwidget_xml(self):
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        plugins_installes = self.getlistplugin_ign()
        for onglet in root.findall("onglet"):
            for plugin in list(onglet.findall("plugin")):
                if plugin.text not in plugins_installes:
                    onglet.remove(plugin)
        ET.indent(root, "    ")
        tree.write(self.path_xml, encoding="utf-8", xml_declaration=True)

    # ==================================================
    # installation des plugins IGN
    def on_show_dial_install_plugins_ign(self):
        self.installer.init_aspect_dialog()
        self.installer.remplir_dlg_plugins()
        self.installer.exec()

    # ==================================================
    # "execution" du plugin en paramètre
    def runplugin(self,plugin):
        try:
            processing_plugin = plugins[plugin]
            processing_plugin.initGui()  # Initialiser l'interface graphique du plugin
            processing_plugin.run()
        except KeyError:
            QMessageBox.warning(None, "Attention",
                f"le plugin {plugin} n'est pas chargé\n"
                f"Veuillez l'activer dans le menu \"Installer/Gérer les extensions de QGIS\"")

    # ==================================================
    # récupérer la liste de tous les plugins IGN installés
    def getlistplugin_ign(self):
        # analyse du dossier
        # ne pas utiliser qgis.utils.available_plugins car le scan se fait qu'apres
        # redémarrage de qgis
        plugins_dir = Path(QgsApplication.qgisSettingsDirPath()) / "python" / "plugins"
        self.plugin_ign = [p.name
            for p in plugins_dir.iterdir()
            if p.is_dir()
               and p.name.startswith(PREFIXE_PLUGIN_IGN)
               and p.name not in EXCEPT_PLUGIN
        ]
        return self.plugin_ign

    # ==================================================
    # retourne une liste avec tous les onglets du xml
    def get_onglet_fromXML(self):
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        onglets = root.findall(".//onglet")
        liste_onglet = []
        for onglet in onglets:
            liste_onglet.append(onglet.get("id"))
        return liste_onglet

    # ==================================================
    # récuperation de tous les onglets du xml
    # et initialisation des onglets du tabwidget
    def init_all_onglet_fromXML(self):
        self.list_onglet.clear()
        tree  =ET.parse(self.path_xml)
        root = tree.getroot()
        onglets = root.findall(".//onglet")
        for onglet in onglets:
            id_onglet = onglet.get("id")
            listWidget = QListWidget()
            if id_onglet != MENU_IGN:
                self.add_allpluginIGN_in_widgetlist(listWidget)
                self.dlg.tabWidget.addTab(listWidget,onglet.get("id"))
                self.list_onglet.append(onglet.get("id"))

    def init_menu_ign_from_xml(self):
        self.list_onglet.clear()
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        onglets = root.findall(".//onglet")
        for onglet in onglets:
            id_onglet = onglet.get("id")
            if id_onglet == MENU_IGN:
                # ajout dans le menu IGN
                self.add_allpluginIGN_in_widgetlist(self.dlg.listWidget_menu_IGN)


    # ==================================================
    # initialisation d'un listwidget avec tous les plugins "IGN" trouvés
    def add_allpluginIGN_in_widgetlist(self, listwidget):
        for plugin in self.plugin_ign:
            if PREFIXE_PLUGIN_IGN in plugin:
                itemtoolbar = QListWidgetItem()
                plugins_dir = Path(QgsApplication.qgisSettingsDirPath(), "python", "plugins")
                icon_path = Path(plugins_dir, plugin, "icons", "icon_principal.png")
                itemtoolbar.setIcon(QIcon(str(icon_path)))
                listwidget.setIconSize(QSize(20, 20))
                itemtoolbar.setFlags(Qt.ItemFlag.ItemIsEnabled | Qt.ItemFlag.ItemIsUserCheckable)
                itemtoolbar.setText(plugin)
                itemtoolbar.setCheckState(Qt.CheckState.Unchecked)
                listwidget.addItem(itemtoolbar)

    # ==================================================
    # retourne une liste de tous les plugins du xml pour un onglet donné
    def get_plugin_coche_fromXML(self,onglet):
        # charge le XML existant
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        onglet_xml = root.find(f".//onglet[@id='{onglet}']")
        list_coche = []
        if onglet_xml is not None:
            for plugin in onglet_xml.findall("plugin"):
                list_coche.append(plugin.text)
        return list_coche

    # ==================================================
    # pour chaque onglet on "coche" ou pas chaque plugin dans le tabwidget
    def init_plugins_coche_in_toolbar(self):
        # la recuperation se fait à partir du tabwidget et non du xml (à voir).
        list_coche = []
        for index in range(self.dlg.tabWidget.count()):
            list_coche.clear()
            widgetlist = self.dlg.tabWidget.widget(index)
            nom = self.dlg.tabWidget.tabText(index)
            list_coche = self.get_plugin_coche_fromXML(nom)

            # pour chaque widgetlist, on coche
            for plugin_coche in list_coche:
                item_find = widgetlist.findItems(plugin_coche, Qt.MatchFlag.MatchExactly)
                if len(item_find) != 0:
                    item_find[0].setText(plugin_coche)
                    item_find[0].setSelected(True)
                    item_find[0].setCheckState(Qt.CheckState.Checked)

    def init_plugin_coche_in_menu_ign(self):
        # recuperation des plugins du xml pour le menu IGN
        list_coche = self.get_plugin_coche_fromXML(MENU_IGN)
        for plugin_coche in list_coche:
            item_find = self.dlg.listWidget_menu_IGN.findItems(plugin_coche, Qt.MatchFlag.MatchExactly)
            if len(item_find) != 0:
                item_find[0].setText(plugin_coche)
                item_find[0].setSelected(True)
                item_find[0].setCheckState(Qt.CheckState.Checked)


    # ==================================================
    # si xml absent : creation d'un xml par défaut avec un plugin par défaut
    def initXML(self):
        # Créer le dossier s'il n'existe pas
        os.makedirs(Path(os.path.dirname(__file__), DOSSIER_ONGLET), exist_ok=True)
        # Racine uniquement
        root = ET.Element("tabwidget")
        ET.SubElement(root, "onglet", id=MENU_IGN)
        # Écriture dans le fichier
        tree = ET.ElementTree(root)
        tree.write(self.path_xml, encoding="utf-8", xml_declaration=True)


    # ==================================================
    # écriture du xml avec tous les plugins cochés en fonction de l'onglet
    def ecrire_plugin_coche_toXML(self,onglet,list_plugin_coche):
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        ongletXml = root.find(f".//onglet[@id='{onglet}']")
        for plugin in list_plugin_coche:
            pluginXml = ET.SubElement(ongletXml,"plugin")
            pluginXml.text = plugin
        ET.indent(root, "    ")
        tree.write(self.path_xml,encoding='utf-8', xml_declaration=True)



    # ==================================================
    # suppression d'un onglet (xml,barre d'outils et tabwidget)
    def supp_onglet(self, index: int):
        nom_onglet = self.dlg.tabWidget.tabText(index)
        text = "Voulez vous vraiment supprimer la barre d'outils :"
        text += "<span style='color:red; font-weight: bold'> " + nom_onglet + "</span> ?"
        if affichemessageAvertissement("Avertissement", text):
            # suppression de l'onglet dans le xml
            self.suppr_ongletXML(index)
            # suppression de l'onglet dans le tabwidget
            self.dlg.tabWidget.removeTab(index)
            # suppression de la barre d'outils
            if hasattr(self, "toolbars") and nom_onglet in self.toolbars:
                self.toolbars[nom_onglet].setParent(None)
                del self.toolbars[nom_onglet]

    # ==================================================
    # suppression de tous les plugins du menu ign
    def supr_plugin_to_menu(self):
        action_to_remove = self.menu.actions()
        for action in action_to_remove:
            self.menu.removeAction(action)

    # ==================================================
    # ajout les plugins aux différentes toolbar en fct du xml
    def add_plugin_in_toolbars(self):
        self.suppr_all_toolbar()
        current_directory = os.path.dirname(__file__)
        # Remonter d'un niveau
        parent_directory = os.path.abspath(Path(current_directory, os.pardir))
        # récupérer les onglets du xml ici et boucler
        for onglet in self.get_onglet_fromXML():
            if onglet != MENU_IGN:
                # si l'onglet n'a pas de plugin défini, on n'ajoute pas à la barre d'outil,
                # mais il reste dans le xml si on veut ajouter des plugins par la suite
                if len(self.get_plugin_coche_fromXML(onglet)) == 0:
                    continue

                self.toolbar = self.iface.addToolBar(onglet)
                self.toolbars[onglet] = self.toolbar
                if onglet != MENU_IGN:
                    # libellé devant chaque barre d'outils
                    label_toolbar = QLabel(onglet)
                    label_toolbar.setStyleSheet(CUSTOM_WIDGETS[1])
                    self.toolbar.addWidget(label_toolbar)

                    for plugincoche in self.get_plugin_coche_fromXML(onglet):
                        icon_path = Path(parent_directory, plugincoche, "icons", "icon_principal.png")
                        action = QAction(QIcon(str(icon_path)), plugincoche, self.iface.mainWindow())
                        action.triggered.connect(
                            lambda checked, plugincoche1=plugincoche: self.runplugin(plugincoche1))
                        # ajout d'un attribut pour utiliser plusieurs instances différentes de self.toolbar
                        setattr(self, onglet, self.toolbar)
                        self.toolbar.addAction(action)

    # ==================================================
    # ajout d'un onglet dans le xml et dans le tabwidget
    def add_onglet(self):
        nom_barre = self.dlgaddonglet.lineEdit_newonglet.text()
        if nom_barre == "":
            return
        for i in range(self.dlg.tabWidget.count()):
            if self.dlg.tabWidget.tabText(i) == nom_barre:
                afficheerreur("Avertissement","Ce nom existe déjà !")
                self.dlgaddonglet.lineEdit_newonglet.clear()
                return
        nb_onglet = self.dlg.tabWidget.count()

        listWidget = QListWidget()
        self.add_allpluginIGN_in_widgetlist(listWidget)
        self.dlg.tabWidget.addTab(listWidget, nom_barre)

        self.dlg.tabWidget.setCurrentIndex(nb_onglet)

        # ecriture du fichier de config correspondant à l'onglet ajouté
        self.add_ongletXML(nom_barre)
        self.dlgaddonglet.hide()

    # ==================================================
    # ouverture du dialogue d'ajout d'un onglet
    def show_dial_add_onglet(self):
        self.dlgaddonglet.lineEdit_newonglet.clear()
        self.dlgaddonglet.lineEdit_newonglet.setFocus()
        self.dlgaddonglet.exec()

    # ==================================================
    # ouverture du dialogue "à propos de..."
    def apropos(self):
        dlgAProposDe = QDialog()
        ui_file = Path(__file__).parent / "ui" / "aproposde.ui"
        loadUi(ui_file, dlgAProposDe)
        dlgAProposDe.setWindowFlags(Qt.WindowType.WindowStaysOnTopHint | Qt.WindowType.WindowCloseButtonHint)
        dlgAProposDe.setWindowTitle(f"{TITRE}")
        dlgAProposDe.pushButtonAffichedoc.clicked.connect(afficheDoc)
        dlgAProposDe.exec()

    # ==================================================
    # renommer un onglet dans le xml
    # et actualisation de l'interface
    def renomme_onglet(self):
        index = self.dlg.tabWidget.currentIndex()
        ancien_nom = self.dlg.tabWidget.tabText(index)
        nouveau_nom,ok =QInputDialog.getText(None,"Renommer la barre d'outils","Nouveau nom :",text = ancien_nom)
        # ... et different du menu IGN
        if ok and nouveau_nom:
            self.dlg.tabWidget.setTabText(index, nouveau_nom)
            tree = ET.parse(self.path_xml)
            root = tree.getroot()
            ongletXml = root.find(f".//onglet[@id='{ancien_nom}']")
            if ongletXml is None:
                return
            # Modifier l’attribut id
            ongletXml.set("id", nouveau_nom)
            ET.indent(tree, "    ")
            tree.write(self.path_xml, encoding="utf-8", xml_declaration=True)
            self.actualiser()

    # ==================================================
    # suppression de tous les plugins du xml
    def suppr_all_plugincoche_toXML(self, onglet):
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        onglet_xml = root.find(f".//onglet[@id='{onglet}']")
        if onglet_xml is not None:
            for plugin in onglet_xml.findall("plugin"):
                onglet_xml.remove(plugin)
            tree.write(self.path_xml, encoding='utf-8', xml_declaration=True)

    # ==================================================
    # suppression d'un onglet dans le xml
    def suppr_ongletXML(self,index):
        tree = ET.parse(self.path_xml)
        root = tree.getroot()
        for onglet in root.findall(".//onglet"):
            if onglet.get("id") == self.dlg.tabWidget.tabText(index):
                root.remove(onglet)
        tree.write(self.path_xml, encoding='utf-8', xml_declaration=True)

    # ==================================================
    # ajout onglet et plugins cochés dans le xml
    def add_ongletXML(self,nom):
        # charge le XML existant
        tree = ET.parse(self.path_xml)
        root = tree.getroot()

        # creation nouvel onglet
        new_onglet = ET.Element("onglet",id = nom)
        root.append(new_onglet)

        # mise en page : indentation
        ET.indent(root, "    ")
        tree.write(self.path_xml, encoding='utf-8', xml_declaration=True)

    def initGui(self):
        # recuperation des infos des plugins du depot officiel si plugins dans le depot officiel
        # sinon recuperation des infos dans le depot github
        # puis comparaison des versions des plugins installés (lecture metadata.txt) avec celles des fichiers XML téléchargé
        list_plugins_to_install = {}
        for depot in ("officiel", "github"):
            for name, infos in self.installer.pluginsIGN.get_plugins_ign_from_depot(depot).items():
                version_installe = get_info_plugins_installe(name,"version")
                if version_installe is not None and version_installe != infos["version"]:
                    list_plugins_to_install[name] = {"version" : infos["version"],
                                                     "download_url": infos["download_url"],
                                                     "icon": infos["icon"]
                                                     }

        if list_plugins_to_install:
            self.maj.init_dial_maj()
            self.maj.show_dial_maj_plugins(list_plugins_to_install)


        self.first_start = True

    def unload(self):
        self.suppr_all_toolbar()
        self.menu.deleteLater()

    # ==================================================
    def run(self):

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = QDialog()
            ui_file = Path(__file__).parent / "ui" / "plugin_maitre_dialog_base.ui"
            loadUi(ui_file, self.dlg)

            self.dlg.setWindowTitle(f"{TITRE}")
            self.dlg.setParent(self.iface.mainWindow())
            self.dlg.setWindowFlags(Qt.WindowType.Dialog | Qt.WindowType.WindowTitleHint | Qt.WindowType.WindowCloseButtonHint)

            # dial d'ajout d'onglet
            self.dlgaddonglet = QDialog()
            ui_file = Path(__file__).parent / "ui" / "add_onglet.ui"
            loadUi(ui_file, self.dlgaddonglet)
            self.dlgaddonglet.setWindowFlags(Qt.WindowType.WindowStaysOnTopHint | Qt.WindowType.WindowCloseButtonHint)
            self.dlgaddonglet.pushButton_addonglet.clicked.connect(self.add_onglet)

            # bouton actualiser la toolbar
            self.dlg.pushButtonActualiser.clicked.connect(self.actualiser)
            self.dlg.pushButtonActualiser.setStyleSheet(CUSTOM_WIDGETS[0])
            # ajouter une toolbar
            self.dlg.pushButtonAddBarre.clicked.connect(self.show_dial_add_onglet)
            # bouton renommer
            self.dlg.pushButton_renommer.clicked.connect(self.renomme_onglet)
            # Connecter le signal 'tabRemoved' à un slot
            self.dlg.tabWidget.tabCloseRequested.connect(self.supp_onglet)

            self.dlg.label_menu.setStyleSheet(CUSTOM_WIDGETS[1])
            self.dlg.label_toolbar.setStyleSheet(CUSTOM_WIDGETS[1])
            # self.dlg.label_titre.setStyleSheet(CUSTOM_WIDGETS[3])
            self.dlg.pushButtonAddBarre.setStyleSheet(CUSTOM_WIDGETS[3])
            self.dlg.pushButton_renommer.setStyleSheet(CUSTOM_WIDGETS[3])


            # suppression
            self.supr_plugin_to_menu()
            # suppression des plugins de la toolbar avant de la réinitialiser
            # self.supr_plugin_to_toolbar()

            # suppr des onglets
            self.dlg.tabWidget.clear()

            # apparence du tabwidget
            self.dlg.tabWidget.setStyleSheet(CUSTOM_WIDGETS[2])

            # recuperation de tous les onglets du xml
            # initialisation des onglets du tabwidget
            self.init_all_onglet_fromXML()
            self.init_menu_ign_from_xml()

            # # initialisation des plugins cochés pour chaque barre d'outils dans le tabwidget
            self.init_plugins_coche_in_toolbar()
            # initialisation des plugins cochés dans le menu IGN
            self.init_plugin_coche_in_menu_ign()


            self.add_plugin_in_toolbars()
            self.init_menuIGN()

            self.dlg.exec()

            self.first_start = True

